      - name: Build iOS
        working-directory: target/${{ inputs.app_dir }}/ios
        run: |
          xcodebuild \
            -workspace "${{ steps.workspace.outputs.workspace }}" \
            -scheme "${{ steps.workspace.outputs.scheme }}" \
            -configuration Release \
            -destination generic/platform=iOS \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            ONLY_ACTIVE_ARCH=NO \
            build
